In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\mohammes\appdata\local\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [1]:
# test the browser
import selenium
from time import sleep
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import pandas as pd

In [24]:
#Question 1
driver = webdriver.Firefox()
driver.get('https://www.totaljobs.com/')
sleep(15)
job_title = driver.find_element(By.ID,"keywords")
job_title.send_keys('Data Scientist')

serach_button = driver.find_element(By.ID,"search-button")
serach_button.click()
sleep(10)

#select location
location = driver.find_element(By.CLASS_NAME,"res-44kvrv")
location.click()
sleep(5)

#select salary
salary = driver.find_element(By.CLASS_NAME,"res-44kvrv")
salary.click()
sleep(5)

In [25]:
job_title=[]
location=[]

In [27]:
#Scrapping the job title
title_tags=driver.find_elements(By.XPATH,"/html/body/div[4]/div[1]/div/div/div[2]/div/div[2]/div[2]/div[1]/div/article[1]/div[1]/h2/a")
for i in title_tags:
    title=i.text
    job_title.append(title)
    
#Scrapping the location
location_tags=driver.find_elements(By.XPATH,"/html/body/div[4]/div[1]/div/div/div[3]/div/div[2]/div[2]/div[1]/div/article[1]/div[1]/div[2]/div[2]/span")
for i in location_tags:
    location=i.text
    location.append(location)

In [101]:
print(len(job_title),len(location))

2 2

In [102]:
#dataframe
df=pd.DataFrame({'Title':job_title,'Location':location})
df

            Title  Location
0               0         0
1  Data Scientist        10

In [20]:
#Question 2
driver = webdriver.Firefox()
driver.get('https://www.shine.com/')
sleep(30)

serach_button = driver.find_element(By.CLASS_NAME,"iconH-zoom-white")
serach_button.click()
sleep(10)

#select JobTitle
job_title = driver.find_element(By.ID,"id_q")
job_title.send_keys('Data Analyst')

#select location
location = driver.find_element(By.ID,"id_loc")
location.send_keys('Bangalore')

button = driver.find_element(By.XPATH,"/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[2]/div/button")
button.click()

In [69]:
job_title=[0]
location=[0,15]

In [70]:
#Scrapping the job title
title_tags=driver.find_elements(By.XPATH,"/html/body/div[1]/div[2]/div[4]/div/div[2]/div[1]/div/div/div[1]/div[1]/div[1]/strong/a")
for i in title_tags:
    title=i.text
    job_title.append(title)
    
#Scrapping the location
location_tags=driver.find_elements(By.CLASS_NAME,"jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2")
for i in location_tags:
    location=i.text
    location.append(location)

In [71]:
print(len(job_title),len(location))

2 2

In [72]:
#dataframe
df=pd.DataFrame({'Title':job_title,'Location':location})
df

                      Title  Location
0                         0         0
1  Data Analyst Recruitment        15

In [2]:
#Question 4
driver = webdriver.Firefox()
driver.get('https://www.amazon.co.uk/')
sleep(5)
           
# search for product
product = driver.find_element(By.ID,"twotabsearchtextbox")
product.send_keys('sneakers')

serach_button = driver.find_element(By.ID,"nav-search-submit-button")
serach_button.click()
sleep(5)

In [18]:
#Brand,ProductDescription and Price
sneakers_brand=[]
sneakers_desc=[]
#sneakers_price=[]

brands = driver.find_elements(By.XPATH,'//span[@class="a-size-base-plus a-color-base"]')
for brand in brands:
    sneakers_brand.append(brand.text)

descrp = driver.find_elements(By.XPATH,'//span[@class="a-size-base-plus a-color-base a-text-normal"]')
for desc in descrp:
    sneakers_desc.append(desc.text)
    
# prices = driver.find_elements(By.XPATH,'//span[@class="a-offscreen"]')
#for price in prices:
#sneakers_price.append(price.text)

print(len(sneakers_brand),len(sneakers_desc))

70 70

In [19]:
#dataframe
df=pd.DataFrame({'Brand':sneakers_brand,'Description':sneakers_desc})
df

         Brand                                        Description
0       adidas                    Unisex's Predator.4 FxG Sneaker
1       adidas  Unisex's Predator Club Turf Football Boots Sne...
2          JCB  Safety Trainers for Men - 100% Spark Metal Fre...
3     JUEQIBAA  Mens Trainers Running Shoes Lightweight Walkin...
4   Rocket Dog             Chow Chow Margate Womens Floral Canvas
..         ...                                                ...
65    Skechers                            Women's Summits Sneaker
66      adidas     Men's Grand Td Lifestyle Court Casual Sneakers
67      adidas     Men's Advantage Premium Leather Shoes Sneakers
68      Reebok                 Unisex's Glide Ripple Clip Sneaker
69         STQ  Womens Walking Shoes Slip-on Lightweight Mesh ...

[70 rows x 2 columns]

In [33]:
#Question 5
driver = webdriver.Firefox()
driver.get('https://www.amazon.co.uk/')
sleep(5)
           
# search for product
product = driver.find_element(By.ID,"twotabsearchtextbox")
product.send_keys('laptop')

serach_button = driver.find_element(By.ID,"nav-search-submit-button")
serach_button.click()
sleep(5)  

cpu_type = driver.find_element(By.ID,"p_n_feature_fifteen_browse-bin-title")
cpu_type.click()
sleep(5)

fliter_cpu_type = driver.find_element(By.LINK_TEXT,"Intel Core i7")
fliter_cpu_type.click()
sleep(5)

In [38]:
#Brand,ratings and Price
laptop_brand=[]
laptop_ratings=[]
#laptop_price=[]

brands[0:30] = driver.find_elements(By.XPATH,'//span[@class="a-size-medium a-color-base a-text-normal"]')
for brand in brands[0:30]:
    laptop_brand.append(brand.text)

ratings[0:30] = driver.find_elements(By.XPATH,'//span[@class="a-size-base s-underline-text"]')
for rate in ratings[0:30]:
    laptop_ratings.append(rate.text)
    
#prices = driver.find_elements(By.XPATH,'//span[@class="a-price"]')
#for price in prices:
#laptop_price.append(price.text)

print(len(laptop_brand),len(laptop_ratings))

30 30

In [39]:
#dataframe
df=pd.DataFrame({'Brand':laptop_brand,'Ratings':laptop_ratings})
df

                                                Brand Ratings
0   Acer Nitro 5 AN515-58 Gaming Laptop - Intel Co...      25
1   Acer Predator Helios Neo 16 PHN16-71 16-inch G...       5
2   ASUS Vivobook Touchscreen X1504VA 15.6" Full H...   1,201
3   Dell Inspiron 15 3530 15.6" FHD Laptop, Intel ...     181
4   Lenovo IdeaPad Slim 5 | 14 inch Full HD OLED L...      28
5   Microsoft Surface Laptop 5 - 15 Inch 2-in-1 Ta...      25
6   KiiUiUi 2 in 1 Laptop, 16GB LDDR5X RAM 1TB PCI...     110
7   Fsjun All-metal 15.6'' 2.5K Screen Laptop Core...     147
8   Dell Latitude 7490 14” FHD Laptop – Core i7-86...   1,201
9   ASUS Vivobook 15 X515JA 15.6" Full HD Laptop (...
10  HP 250 G9 Laptop, Intel Core i7-1255U up to 4....      58
11  ASUS TUF Gaming FX707VI 17.3" Full HD 144Hz Ga...       1
12  ASUS Vivobook 15 X1504ZA 15.6" Full HD Laptop ...      35
13  ASUS Vivobook 15 X1504ZA 15.6" Full HD Laptop ...     190
14  Dell Inspiron 14 7430 2-in-1 Laptop, 13th Gene...       4
15  Lenovo ThinkPad T480 Windows 11 Pro Ultrabook ...     568
16  Lenovo IdeaPad Slim 3 | 15 inch Full HD Laptop...   1,201
17  ASUS Zenbook S13 OLED UX5304MA 13.3" 2.8K OLED...   1,201
18  Dell G15 5530 15.6-inch FHD 165 Hz Gaming Lapt...     115
19  ASUS Laptop Vivobook 16 K3605ZV 16.0" 120Hz Fu...       5
20  HP EliteBook 850 G5 15.6” Laptop – Intel Core ...      65
21  ASUS VivoBook 17 X1704ZA-AU037W Laptop 43.9 cm...     147
22  Lenovo IdeaPad 3 Business Professional Laptop,...      29
23  HP EliteBook x360 1040 G8 2-in-1 Touchscreen L...      59
24  Dell XPS 13 9315 Laptop, 12th Gen Intel Evo Co...      11
25  MSI Stealth 14 Studio A13VE-029-14" FHD+ 165Hz...       4
26  ASUS VivoBook 15 X1504ZA 15.6-inch Laptop (Int...       5
27  HP Elitebook 840 G3 Laptop Intel i7-6600U 2.6G...       4
28  Microsoft Surface Laptop 4 Super-Thin 13.5 Inc...      22
29  ThinkPad L13 Gen 2 (13.3") FHD Laptop - 11th G...       2

In [2]:
#Question 6
driver = webdriver.Firefox()
driver.get('https://www.azquotes.com/')
sleep(10)

top_quotes = driver.find_element(By.XPATH,'//*[@id="menu"]/div/div[3]/ul/li[5]/a')
top_quotes.click()
sleep(5)

In [6]:

list_author=[]
list_quotes=[]
type_quotes=[]

authors[0:30] = driver.find_elements(By.XPATH,'//span[@class="author"]')
for author in authors[0:30]:
    list_author.append(author.text)

quotes[0:30] = driver.find_elements(By.XPATH,'//span[@class="title"]')
for quote in quotes[0:30]:
    list_quotes.append(quote.text)

tquotes[0:30] = driver.find_elements(By.XPATH,'//span[@class="tags"]')
for tquote in tquotes[0:30]:
    type_quotes.apend(tquote.text)

print(len(list_author),len(list_quotes),len(type_quotes))

0 0 0

In [7]:
#Question 7
driver = webdriver.Firefox()
driver.get('https://www.jagranjosh.com/general-knowledge/list-of-all-prime-ministers-of-india-1473165149-1')
sleep(5)
# In this website there is no class or id and Xpath keep on change and there no parent path only text
#is given in each field not possiable do the dataframe

In [15]:
#QUESTION 8
driver = webdriver.Firefox()
driver.get('https://www.motor1.com/')
sleep(8)
           
# search for product
product = driver.find_element(By.ID,"search_input")
product.send_keys('50 most expensive cars')
sleep(2)

serach_button = driver.find_element(By.CLASS_NAME,"m1-search-panel-button m1-search-form-button-animate icon-search-svg")
serach_button.click()
sleep(5)  

cpu_type = driver.find_element(By.XPATH,'//*[@id="page_index_articles_search"]/div[9]/div/div[1]/div/div/div[1]/div/div[1]/h3/a')
cpu_type.click()
sleep(5)
# there is issue with search button not taking any Locators

NoSuchElementException: Message: Unable to locate element: .m1-search-panel-button m1-search-form-button-animate icon-search-svg; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:192:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:510:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

In [ ]:
#Question3 - There the website is access deneied in UK